### ISSUE TITLE
Using move buttons during a line clear causes panic

### ISSUE THREAD

**Issue by Wryte** [AntonKosov/tetrominos#31]
Steps to reproduce:

1. Clear a line
2. While line clears press the right arrow
3. Observe panic

![image](https://user-images.githubusercontent.com/1534358/143478853-e98e5742-9dc7-4652-8509-faa0a98a4eef.png)

**Comment by BoldAntonKosov** [comment]
@Wryte Oops :) Thanks!

**Comment by AntonKosov** [comment]
@Wryte Oops. Thanks!
